version: 2.1

orbs:
  aws-eks: circleci/aws-eks@2.2.0
  kubernetes: circleci/kubernetes@1.2.0

jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            # Install hadolint
             wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
               chmod +x /bin/hadolint
      - run:
          name: Linting
          command: |
            hadolint Dockerfile
  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Build application Docker image
          command: docker build -t uda_cloud_devops_capstone .
      - run:
          name: Docker login
          command: |
            echo ${DOCKER_HUB_PASSWORD} | docker login -u ${DOCKER_HUB_USERNAME} --password-stdin
      - run:
          name: Push Docker Image
          command: |
            docker tag uda_cloud_devops_capstone canhnv/uda_cloud_devops_capstone
            docker push canhnv/uda_cloud_devops_capstone
  deploy:
    docker:
      - image: python:3.7.3-stretch
    parameters:
      cluster-name:
        description: |
          Name of the EKS cluster
        type: string
        default: "CapstoneEKS-gRE6KE8slweW"
      aws-region:
        description: |
          AWS region
        type: string
        default: "us-east-1"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - kubernetes/install-kubectl
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.cluster-name >>
          aws-region: << parameters.aws-region >>
          install-kubectl: true
      - kubernetes/create-or-update-resource:
          resource-file-path: ./k8s/configmap.yml
          resource-name: configmap/ aws-auth

      - kubernetes/create-or-update-resource:
          resource-file-path: ./k8s/deployment.yml
          resource-name: deployment/uda-cloud-devops-capstone
          get-rollout-status: true
          show-kubectl-command: true
workflows:
  default:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - deploy:
          requires:
            - build
